package main.junctionframework;

import main.world.Direction;
import main.world.Simulator;

import javax.swing.JFrame;
import java.awt.*;

public class MainFrame extends JFrame {

	private Simulator simulator;

	public MainFrame(Simulator simulator) {
		super("Junction Framework");

		this.simulator = simulator;
		
		initComponents();
	}

	public void refresh() {
		this.repaint();

		//calculate the values
	}

	private void redNewVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:

		simulator.changeColor(Direction.RED);
    }                                                   

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void purpleNewVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void orangeNewVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
    }                                                      

    private void blueNewVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void speedSliderCaretPositionChanged(java.awt.event.InputMethodEvent evt) {                                                 
        // TODO add your handling code here:
    }  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        junctionPanel = new javax.swing.JPanel();
        redNewVehicleButton = new javax.swing.JButton();
        purpleNewVehicleButton = new javax.swing.JButton();
        blueNewVehicleButton = new javax.swing.JButton();
        orangeNewVehicleButton = new javax.swing.JButton();
        speedSlider = new javax.swing.JSlider();
        speedLabel = new javax.swing.JLabel();
        redPanel = new javax.swing.JPanel();
        bluePanel = new javax.swing.JPanel();
        orangePanel = new javax.swing.JPanel();
        purplePanel = new javax.swing.JPanel();
        stopButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        redLampPanel = new javax.swing.JPanel();
        orangeLampPanel = new javax.swing.JPanel();
        purpleLampPanel = new javax.swing.JPanel();
        blueLampPanel = new javax.swing.JPanel();
        redInfoPanel = new javax.swing.JPanel();
        redDelayLabel = new javax.swing.JLabel();
        redDelayValueLabel = new javax.swing.JLabel();
        redCarSumLabel = new javax.swing.JLabel();
        redCarSumValueLabel = new javax.swing.JLabel();
        blueInfoPanel = new javax.swing.JPanel();
        blueDelayLabel = new javax.swing.JLabel();
        blueDelayValueLabel = new javax.swing.JLabel();
        blueCarSumLabel = new javax.swing.JLabel();
        blueCarSumValueLabel = new javax.swing.JLabel();
        orangeInfoPanel = new javax.swing.JPanel();
        orangeDelayLabel = new javax.swing.JLabel();
        orangeDelayValueLabel = new javax.swing.JLabel();
        orangeCarSumLabel = new javax.swing.JLabel();
        orangeCarSumValueLabel = new javax.swing.JLabel();
        purpleInfoPanel = new javax.swing.JPanel();
        purpleDelayLabel = new javax.swing.JLabel();
        purpleDelayValueLabel = new javax.swing.JLabel();
        purpleCarSumLabel = new javax.swing.JLabel();
        purpleCarSumValueLabel = new javax.swing.JLabel();
        elapsedTimeLabel = new javax.swing.JLabel();
        elapsedTimeValue = new javax.swing.JLabel();
        blueLampLeftPanel = new javax.swing.JPanel();
        orangeLampRightPanel = new javax.swing.JPanel();
        blueLampRightPanel = new javax.swing.JPanel();
        purpleLampLeftPanel = new javax.swing.JPanel();
        orangeLampLeftPanel = new javax.swing.JPanel();
        purpleLampRightPanel = new javax.swing.JPanel();
        redLampRightPanel = new javax.swing.JPanel();
        redLampLeftPanel = new javax.swing.JPanel();

        // settings
        String newVehicleButtonText = "new vehicle";
        String delaySumLabelText = "delay sum:";
        String carsSumLabelText = "cars sum:";
        Font font = new Font("Segoe UI",1,12);
        Color purpleColor = new java.awt.Color(153, 0, 153);
        Color orangeColor = new java.awt.Color(255, 153, 0);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        junctionPanel.setBackground(Color.GREEN);
        junctionPanel.setPreferredSize(new java.awt.Dimension(260, 260));

        javax.swing.GroupLayout junctionPanelLayout = new javax.swing.GroupLayout(junctionPanel);
        junctionPanel.setLayout(junctionPanelLayout);
        junctionPanelLayout.setHorizontalGroup(
            junctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        junctionPanelLayout.setVerticalGroup(
            junctionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        redNewVehicleButton.setBackground(Color.RED);
        redNewVehicleButton.setText(newVehicleButtonText);
        redNewVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redNewVehicleButtonActionPerformed(evt);
            }
        });

        purpleNewVehicleButton.setBackground(purpleColor);
        purpleNewVehicleButton.setText(newVehicleButtonText);
        purpleNewVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purpleNewVehicleButtonActionPerformed(evt);
            }
        });

        blueNewVehicleButton.setBackground(Color.BLUE);
        blueNewVehicleButton.setText(newVehicleButtonText);
        blueNewVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueNewVehicleButtonActionPerformed(evt);
            }
        });

        orangeNewVehicleButton.setBackground(orangeColor);
        orangeNewVehicleButton.setText(newVehicleButtonText);
        orangeNewVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeNewVehicleButtonActionPerformed(evt);
            }
        });

        speedSlider.setMaximum(1000);
        speedSlider.setMinimum(1);
        speedSlider.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                speedSliderCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        speedLabel.setFont(font); // NOI18N
        speedLabel.setText("Speed");

        redPanel.setBackground(Color.RED);

        javax.swing.GroupLayout redPanelLayout = new javax.swing.GroupLayout(redPanel);
        redPanel.setLayout(redPanelLayout);
        redPanelLayout.setHorizontalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        redPanelLayout.setVerticalGroup(
            redPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        bluePanel.setBackground(Color.BLUE);

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        orangePanel.setBackground(orangeColor);

        javax.swing.GroupLayout orangePanelLayout = new javax.swing.GroupLayout(orangePanel);
        orangePanel.setLayout(orangePanelLayout);
        orangePanelLayout.setHorizontalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        orangePanelLayout.setVerticalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        purplePanel.setBackground(purpleColor);

        javax.swing.GroupLayout purplePanelLayout = new javax.swing.GroupLayout(purplePanel);
        purplePanel.setLayout(purplePanelLayout);
        purplePanelLayout.setHorizontalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        purplePanelLayout.setVerticalGroup(
            purplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        stopButton.setFont(font); // NOI18N
        stopButton.setText("stop");
        stopButton.setToolTipText("");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        startButton.setFont(font); // NOI18N
        startButton.setText("start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        redLampPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout redLampPanelLayout = new javax.swing.GroupLayout(redLampPanel);
        redLampPanel.setLayout(redLampPanelLayout);
        redLampPanelLayout.setHorizontalGroup(
            redLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        redLampPanelLayout.setVerticalGroup(
            redLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        orangeLampPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout orangeLampPanelLayout = new javax.swing.GroupLayout(orangeLampPanel);
        orangeLampPanel.setLayout(orangeLampPanelLayout);
        orangeLampPanelLayout.setHorizontalGroup(
            orangeLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        orangeLampPanelLayout.setVerticalGroup(
            orangeLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        purpleLampPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout purpleLampPanelLayout = new javax.swing.GroupLayout(purpleLampPanel);
        purpleLampPanel.setLayout(purpleLampPanelLayout);
        purpleLampPanelLayout.setHorizontalGroup(
            purpleLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        purpleLampPanelLayout.setVerticalGroup(
            purpleLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        blueLampPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout blueLampPanelLayout = new javax.swing.GroupLayout(blueLampPanel);
        blueLampPanel.setLayout(blueLampPanelLayout);
        blueLampPanelLayout.setHorizontalGroup(
            blueLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        blueLampPanelLayout.setVerticalGroup(
            blueLampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        redDelayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redDelayLabel.setText(delaySumLabelText);

        redDelayValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redDelayValueLabel.setText("0");

        redCarSumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redCarSumLabel.setText(carsSumLabelText);

        redCarSumValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        redCarSumValueLabel.setText("0");

        javax.swing.GroupLayout redInfoPanelLayout = new javax.swing.GroupLayout(redInfoPanel);
        redInfoPanel.setLayout(redInfoPanelLayout);
        redInfoPanelLayout.setHorizontalGroup(
            redInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(redInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(redDelayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(redDelayValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redCarSumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redCarSumValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        redInfoPanelLayout.setVerticalGroup(
            redInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(redInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redDelayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redDelayValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redCarSumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redCarSumValueLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        blueDelayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueDelayLabel.setText(delaySumLabelText);

        blueDelayValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueDelayValueLabel.setText("0");

        blueCarSumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueCarSumLabel.setText(carsSumLabelText);

        blueCarSumValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        blueCarSumValueLabel.setText("0");

        javax.swing.GroupLayout blueInfoPanelLayout = new javax.swing.GroupLayout(blueInfoPanel);
        blueInfoPanel.setLayout(blueInfoPanelLayout);
        blueInfoPanelLayout.setHorizontalGroup(
            blueInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(blueInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueDelayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(blueDelayValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueCarSumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueCarSumValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        blueInfoPanelLayout.setVerticalGroup(
            blueInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(blueInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blueDelayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blueDelayValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blueCarSumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blueCarSumValueLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        orangeDelayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangeDelayLabel.setText(delaySumLabelText);

        orangeDelayValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangeDelayValueLabel.setText("0");

        orangeCarSumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangeCarSumLabel.setText(carsSumLabelText);

        orangeCarSumValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orangeCarSumValueLabel.setText("0");

        javax.swing.GroupLayout orangeInfoPanelLayout = new javax.swing.GroupLayout(orangeInfoPanel);
        orangeInfoPanel.setLayout(orangeInfoPanelLayout);
        orangeInfoPanelLayout.setHorizontalGroup(
            orangeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orangeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orangeDelayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(orangeDelayValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeCarSumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeCarSumValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        orangeInfoPanelLayout.setVerticalGroup(
            orangeInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangeInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orangeDelayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orangeDelayValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orangeCarSumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orangeCarSumValueLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        purpleDelayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purpleDelayLabel.setText(delaySumLabelText);

        purpleDelayValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purpleDelayValueLabel.setText("0");

        purpleCarSumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purpleCarSumLabel.setText(carsSumLabelText);

        purpleCarSumValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        purpleCarSumValueLabel.setText("0");

        javax.swing.GroupLayout purpleInfoPanelLayout = new javax.swing.GroupLayout(purpleInfoPanel);
        purpleInfoPanel.setLayout(purpleInfoPanelLayout);
        purpleInfoPanelLayout.setHorizontalGroup(
            purpleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purpleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(purpleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(purpleDelayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(purpleDelayValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purpleCarSumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purpleCarSumValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        purpleInfoPanelLayout.setVerticalGroup(
            purpleInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purpleInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purpleDelayLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purpleDelayValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purpleCarSumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purpleCarSumValueLabel)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        elapsedTimeLabel.setText("Elapsed time:");

        elapsedTimeValue.setText("0");

        blueLampLeftPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout blueLampLeftPanelLayout = new javax.swing.GroupLayout(blueLampLeftPanel);
        blueLampLeftPanel.setLayout(blueLampLeftPanelLayout);
        blueLampLeftPanelLayout.setHorizontalGroup(
            blueLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        blueLampLeftPanelLayout.setVerticalGroup(
            blueLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        orangeLampRightPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout orangeLampRightPanelLayout = new javax.swing.GroupLayout(orangeLampRightPanel);
        orangeLampRightPanel.setLayout(orangeLampRightPanelLayout);
        orangeLampRightPanelLayout.setHorizontalGroup(
            orangeLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        orangeLampRightPanelLayout.setVerticalGroup(
            orangeLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        blueLampRightPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout blueLampRightPanelLayout = new javax.swing.GroupLayout(blueLampRightPanel);
        blueLampRightPanel.setLayout(blueLampRightPanelLayout);
        blueLampRightPanelLayout.setHorizontalGroup(
            blueLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        blueLampRightPanelLayout.setVerticalGroup(
            blueLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        purpleLampLeftPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout purpleLampLeftPanelLayout = new javax.swing.GroupLayout(purpleLampLeftPanel);
        purpleLampLeftPanel.setLayout(purpleLampLeftPanelLayout);
        purpleLampLeftPanelLayout.setHorizontalGroup(
            purpleLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        purpleLampLeftPanelLayout.setVerticalGroup(
            purpleLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        orangeLampLeftPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout orangeLampLeftPanelLayout = new javax.swing.GroupLayout(orangeLampLeftPanel);
        orangeLampLeftPanel.setLayout(orangeLampLeftPanelLayout);
        orangeLampLeftPanelLayout.setHorizontalGroup(
            orangeLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        orangeLampLeftPanelLayout.setVerticalGroup(
            orangeLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        purpleLampRightPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout purpleLampRightPanelLayout = new javax.swing.GroupLayout(purpleLampRightPanel);
        purpleLampRightPanel.setLayout(purpleLampRightPanelLayout);
        purpleLampRightPanelLayout.setHorizontalGroup(
            purpleLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        purpleLampRightPanelLayout.setVerticalGroup(
            purpleLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        redLampRightPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout redLampRightPanelLayout = new javax.swing.GroupLayout(redLampRightPanel);
        redLampRightPanel.setLayout(redLampRightPanelLayout);
        redLampRightPanelLayout.setHorizontalGroup(
            redLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        redLampRightPanelLayout.setVerticalGroup(
            redLampRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        redLampLeftPanel.setBackground(Color.BLACK);

        javax.swing.GroupLayout redLampLeftPanelLayout = new javax.swing.GroupLayout(redLampLeftPanel);
        redLampLeftPanel.setLayout(redLampLeftPanelLayout);
        redLampLeftPanelLayout.setHorizontalGroup(
            redLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        redLampLeftPanelLayout.setVerticalGroup(
            redLampLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangeNewVehicleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(elapsedTimeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(elapsedTimeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(orangeInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orangeLampRightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orangeLampLeftPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orangeLampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(purpleNewVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(purplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(purpleInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(purpleLampRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purpleLampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purpleLampLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(blueInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(blueLampLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(blueLampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(blueLampRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(blueNewVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(junctionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(redLampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redLampRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redLampLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(redInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(redNewVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(speedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(speedSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stopButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speedLabel)
                    .addComponent(speedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopButton)
                    .addComponent(startButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(elapsedTimeLabel)
                            .addComponent(elapsedTimeValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(orangeLampLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orangeLampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orangeLampRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(orangeInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orangeNewVehicleButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(purpleInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purpleLampRightPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purpleLampPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purpleLampLeftPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(purpleNewVehicleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(purplePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(junctionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(redNewVehicleButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(redInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(redLampRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(redLampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(redLampLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(blueLampRightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueLampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blueLampLeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(blueInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blueNewVehicleButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>      


    // Variables declaration - do not modify                     
    private javax.swing.JLabel blueCarSumLabel;
    private javax.swing.JLabel blueCarSumValueLabel;
    private javax.swing.JLabel blueDelayLabel;
    private javax.swing.JLabel blueDelayValueLabel;
    private javax.swing.JPanel blueInfoPanel;
    private javax.swing.JPanel blueLampLeftPanel;
    private javax.swing.JPanel blueLampPanel;
    private javax.swing.JPanel blueLampRightPanel;
    private javax.swing.JButton blueNewVehicleButton;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JLabel elapsedTimeLabel;
    private javax.swing.JLabel elapsedTimeValue;
    private javax.swing.JPanel junctionPanel;
    private javax.swing.JLabel orangeCarSumLabel;
    private javax.swing.JLabel orangeCarSumValueLabel;
    private javax.swing.JLabel orangeDelayLabel;
    private javax.swing.JLabel orangeDelayValueLabel;
    private javax.swing.JPanel orangeInfoPanel;
    private javax.swing.JPanel orangeLampLeftPanel;
    private javax.swing.JPanel orangeLampPanel;
    private javax.swing.JPanel orangeLampRightPanel;
    private javax.swing.JButton orangeNewVehicleButton;
    private javax.swing.JPanel orangePanel;
    private javax.swing.JLabel purpleCarSumLabel;
    private javax.swing.JLabel purpleCarSumValueLabel;
    private javax.swing.JLabel purpleDelayLabel;
    private javax.swing.JLabel purpleDelayValueLabel;
    private javax.swing.JPanel purpleInfoPanel;
    private javax.swing.JPanel purpleLampLeftPanel;
    private javax.swing.JPanel purpleLampPanel;
    private javax.swing.JPanel purpleLampRightPanel;
    private javax.swing.JButton purpleNewVehicleButton;
    private javax.swing.JPanel purplePanel;
    private javax.swing.JLabel redCarSumLabel;
    private javax.swing.JLabel redCarSumValueLabel;
    private javax.swing.JLabel redDelayLabel;
    private javax.swing.JLabel redDelayValueLabel;
    private javax.swing.JPanel redInfoPanel;
    private javax.swing.JPanel redLampLeftPanel;
    private javax.swing.JPanel redLampPanel;
    private javax.swing.JPanel redLampRightPanel;
    private javax.swing.JButton redNewVehicleButton;
    private javax.swing.JPanel redPanel;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration                   
}
